### ISSUE TITLE
Upgrade to Node 20

### ISSUE THREAD

**Issue by leashjay** [bibipkins/dotnet-test-reporter#44]
Could you please consider upgrading to Node 20

running GitHub Actions with
```yaml
      - name: Display test results
        uses: bibipkins/dotnet-test-reporter@v1.3.3
        with:
          github-token: ***
          comment-title: 'Test Results'
          results-path: ***
          coverage-path: ***/coverage.cobertura.xml'
          coverage-type: cobertura
```
Issues the following warning:

```bash
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: bibipkins/dotnet-test-reporter@v1.3.3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```
