### ISSUE TITLE
Failed tests aren't reported when coverage report is missing

### ISSUE THREAD

**Issue by erikljung** [bibipkins/dotnet-test-reporter#51]
Hi and thanks for a great project. 

When running the following `dotnet test` command, and any test fails, then no coverage report will be written. If your action cannot find a coverage report (coverage-path) then it will fail to report the failed tests to summary. The expected behavior would be to report the failed tests and not report any coverage (since there cannot be a complete coverage without all tests succeeding). The current workaround is to have an "empty" `coverage.opencover.xml` with the following content in the coverage-path location:
```
<?xml version="1.0" encoding="utf-8"?>
<CoverageSession>
  <Summary
    numSequencePoints="0"
    visitedSequencePoints="0"
    numBranchPoints="0"
    visitedBranchPoints="0"
    sequenceCoverage="0"
    branchCoverage="0"
    maxCyclomaticComplexity="0"
    minCyclomaticComplexity="0"
    visitedClasses="0"
    numClasses="0"
    visitedMethods="0"
    numMethods="0" />
  <Modules></Modules>
</CoverageSession>
```

```
run: |
  dotnet test \
  --configuration Release \
  --no-build \
  --logger trx \
  --results-directory TestResults \
  /p:CollectCoverage=true \
  /p:CoverletOutputFormat=opencover
```

```
uses: bibipkins/dotnet-test-reporter@v1.4.0
# Run even if tests fails.
if: ${{ always() }}
with:
  github-token: ${{ secrets.GITHUB_TOKEN }}
  comment-title: 'Test results'
  allow-failed-tests: true
  results-path: "${{ env.WORK_DIR }}/TestResults/*.trx"
  coverage-path: "${{ env.WORK_DIR }}/tests/Tests.Main/coverage.opencover.xml"
  coverage-threshold: 50
```
