### ISSUE TITLE
Failed to post a comment

### ISSUE THREAD

**Issue by bt-abarber** [bibipkins/dotnet-test-reporter#54]
I am attempting to only analyze a .trx file and post results for a workflow I have. I am using the following:

```
uses: bibipkins/dotnet-test-reporter@v1.4.0
with:
  github-token: ${{ secrets.GITHUB_TOKEN }}
  comment-title: 'Unit Test Results'
  results-path: ./TestResults/*.trx
```

The output for the job appears like everything is being passed in as expected:

```
Run bibipkins/dotnet-test-reporter@v1.4.0
  with:
    github-token: ***
    comment-title: My Test Results
    results-path: ./TestResults/*.trx
    coverage-type: opencover
    post-new-comment: false
    allow-failed-tests: false
    show-failed-tests-only: false
    show-test-output: true
```

I have a success message stating '_Processed \TestResults\my_testResults.trx_' however immediately after I get another saying '_Failed to post a comment_' and that's it - nothing is generated, no other errors are shown, nothing at all helpful to diagnose what's going on.

**Comment by bothzoli** [comment]
hey @bt-abarber,
I'm just adding this task to my workflow for the first time, so I'm not sure how it works.
however, I believe the task would post a comment to a PR if it was triggered by it.
if you don't want that, you can set `post-new-comment` to `false` and I think that error should go away.

**Comment by bibipkins** [comment]
Sorry for the late response @bt-abarber ! If you are still using this please let me know if the issue still persists. Have you tried version `1.4.1`?

**Comment by patrickmoore-nc** [comment]
I also see this issue. I have tried 1.4.1 and just now 1.5.3. My job has this permission:
```
    permissions:
      pull-requests: write
```
but I've also tried:
```
    permissions:
      pull-requests: write
      contents: read
      actions: read
```
without success. Same error as OP.

The step is configured as follows:
```
      - name: Report results
        uses: bibipkins/dotnet-test-reporter@v1.5.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          comment-title: Unit Test Results
          results-path: aggregated-results/**/*.${{ inputs.unit_test_logger_format }}
```
