### ISSUE TITLE
Failed coverage, when coverage is above threshold

### ISSUE THREAD

**Issue by erikljung** [bibipkins/dotnet-test-reporter#68]
Hi, and thanks for a great project. I've recently switched from OpenCover to Cobertura, OpenCover seems deprecated and is not really supported natively by the "new" Microsoft.Testing.Platform. 

To my issue. When I used OpenCover and v1.4.1 the same project successfully passed coverage, but since the change to Cobertura it suddenly fail. I'm not really sure what to expect here, the project percentage of _~94%_ seems accurate in both cases – and that is what other tools report as well. Could you please give me some advice here?

## Cobertura and v1.5.4
![Image](https://github.com/user-attachments/assets/b2e67f02-7758-4bf0-9288-ef97959d09e2)
```
- name: Report test and coverage results
  uses: bibipkins/dotnet-test-reporter@v1.5.4
  if: ${{ always() }}
  with:
    github-token: ${{ secrets.GITHUB_TOKEN }}
    comment-title: 'Test results'
    allow-failed-tests: true
    results-path: "**/*.trx"
    coverage-path: "${{ env.BACKEND_DIR }}/merged.coverage.xml"
    coverage-threshold: 90
    coverage-type: cobertura
```

## OpenCover and v1.4.1
![Image](https://github.com/user-attachments/assets/a213019d-c229-4bc1-87c1-245455a1e19e)
